name: WPCS check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          paths: './plugnmeet'
          excludes: './plugnmeet/helpers/libs/plugnmeet-sdk-php'
